# Generated by Django 4.0.4 on 2022-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pokemon_fieldnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
